import { Product } from "@/types";

export const products: Product[] = [
    {
        id: "1",
        title: "Running Shoes",
        price: 99,
        image: "/images/shoes.png",
        category: "Clothing",
        rating: 4.5,
        description: "Comfortable running shoes for daily use.",
    },
    {
        id: "2",
        title: "Wireless Headphones",
        price: 199,
        image: "/images/headphones.png",
        category: "Electronics",
        rating: 4.2,
        description: "Noise-cancelling wireless headphones.",
    },
    {
        id: "3",
        title: "Backpack",
        price: 129,
        image: "/images/backpack.png",
        category: "Accessories",
        rating: 4.8,
        description: "Durable backpack for travel and work.",
    },
    {
        id: "4",
        title: "Smartwatch",
        price: 249,
        image: "/images/watch.png",
        category: "Electronics",
        rating: 4.6,
        description: "Track your fitness and stay connected.",
    },
    {
        id: "5",
        title: "Sunglasses",
        price: 149,
        image: "/images/sunglasses.png",
        category: "Accessories",
        rating: 4.3,
        description: "Stylish sunglasses with UV protection.",
    },
    {
        id: "6",
        title: "Digital Camera",
        price: 499,
        image: "/images/camera.png",
        category: "Electronics",
        rating: 4.7,
        description: "Capture life's moments in high resolution.",
    },
    {
        id: "7",
        title: "Smartphone",
        price: 699,
        image: "/images/phone.png",
        category: "Electronics",
        rating: 4.9,
        description: "Latest generation smartphone with powerful features.",
    },
    {
        id: "8",
        title: "T-shirt",
        price: 29,
        image: "/images/tshirt.png",
        category: "Clothing",
        rating: 4.0,
        description: "Soft cotton t-shirt available in multiple colors.",
    },
];
