import { Product } from "@/types";

export const products: Product[] = [
    {
        id: "1",
        title: "Running Shoes",
        price: 99,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=500&q=60",
        category: "Clothing",
        rating: 4.5,
        description: "Comfortable running shoes for daily use.",
    },
    {
        id: "2",
        title: "Wireless Headphones",
        price: 199,
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=500&q=60",
        category: "Electronics",
        rating: 4.2,
        description: "Noise-cancelling wireless headphones.",
    },
    {
        id: "3",
        title: "Backpack",
        price: 129,
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=500&q=60",
        category: "Accessories",
        rating: 4.8,
        description: "Durable backpack for travel and work.",
    },
    {
        id: "4",
        title: "Smartwatch",
        price: 249,
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=500&q=60",
        category: "Electronics",
        rating: 4.6,
        description: "Track your fitness and stay connected.",
    },
    {
        id: "5",
        title: "Sunglasses",
        price: 149,
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=500&q=60",
        category: "Accessories",
        rating: 4.3,
        description: "Stylish sunglasses with UV protection.",
    },
    {
        id: "6",
        title: "Digital Camera",
        price: 499,
        image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=500&q=60",
        category: "Electronics",
        rating: 4.7,
        description: "Capture life's moments in high resolution.",
    },
    {
        id: "7",
        title: "Smartphone",
        price: 699,
        image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=500&q=60",
        category: "Electronics",
        rating: 4.9,
        description: "Latest generation smartphone with powerful features.",
    },
    {
        id: "8",
        title: "T-shirt",
        price: 29,
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=500&q=60",
        category: "Clothing",
        rating: 4.0,
        description: "Soft cotton t-shirt available in multiple colors.",
    },
];
